### ISSUE TITLE
python3.9不支持

### ISSUE THREAD

**Issue by geoyee** [fiyen/PaddlePaddle-DocCRT#2]
python3.9版本，按照requirements安装了依赖库，使用`python main.py`运行，报错：
```
TypeError: can't apply this __setattr__ to Page object
```
网上查阅可能为python版本问题，降至python3.8.2后正常运行。
大佬们可以考虑解决下这个问题，或者在readme中提示一下python的版本。

**Comment by fiyen** [comment]
> python3.9版本，按照requirements安装了依赖库，使用`python main.py`运行，报错：
> 
> ```
> TypeError: can't apply this __setattr__ to Page object
> ```
> 
> 网上查阅可能为python版本问题，降至python3.8.2后正常运行。 大佬们可以考虑解决下这个问题，或者在readme中提示一下python的版本。

你好，这个是基于python3.7开发的。感谢反馈，我马上加一个说明。

**Comment by geoyee** [comment]
> > python3.9版本，按照requirements安装了依赖库，使用`python main.py`运行，报错：
> > ```
> > TypeError: can't apply this __setattr__ to Page object
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 网上查阅可能为python版本问题，降至python3.8.2后正常运行。 大佬们可以考虑解决下这个问题，或者在readme中提示一下python的版本。
> 
> 你好，这个是基于python3.7开发的。感谢反馈，我马上加一个说明。

哈哈，好的辛苦
